base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
show_authors: True
show_links: True
show_badge: True
max_results: 3

publish_readme: False
publish_gitpage: False
publish_wechat: False
publish_lark: True

# file paths
json_readme_path: './docs/agent-arxiv-daily.json'
json_lark_path: './docs/agent-arxiv-daily.json'

md_readme_path: 'README.md'


keywords:
    "agent":
        filters: ["LLM based agents","Large Language Model based agents","LLM agent"]
    "rag":
        filters: ["Retrieval-Augmented Generation","LLM RAG","KG"]
    "llm":
        filters: ["Large Language Model"]